# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Prepare system
      run: |
        sudo apt-get install liblzma-devel
        sudo apt-get install libjpeg-devel
        sudo apt-get install libz-devel
        sudo apt-get install libXau-devel
        sudo apt-get install libXdmcp-devel
        sudo apt-get install libpng16-devel
        sudo apt-get install libwebp-devel
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Build binary
      run: |
        python setup.py build
